### ISSUE TITLE
Make Text Bigger, Add Padding, Make Textarea's Bigger

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/lume#30]
Also check on ipad.

**Comment by michielvanhaverbeke** [comment]
Hello does this issue still need resolving? I would like to contribute

**Comment by carlpeaslee** [comment]
Hi @michielvanhaverbeke! Thanks for being interested in contributing! I'm sorry I haven't done a great job of keeping these issues up to date and I believe this one mostly got taken care of. I might be able to find something else you could contribute to. What sort of things do you like to work on?

**Comment by michielvanhaverbeke** [comment]
Hi!

I'm new to all this and haven't really contributed before. Is there
anything small and rather simple in css or js I could do for you? Just to
get the hang of the contribute process. Btw your project looks awesome
great job!

Yours sincerely Michiel Vanhaverbeke

On Jan 2, 2018 4:34 PM, "Carl Peaslee" <notifications@github.com> wrote:

Hi @michielvanhaverbeke <https://github.com/michielvanhaverbeke>! Thanks
for being interested in contributing! I'm sorry I haven't done a great job
of keeping these issues up to date and I believe this one mostly got taken
care of. I might be able to find something else you could contribute to.
What sort of things do you like to work on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/artsmia/lume/issues/30#issuecomment-354793052>, or mute
the thread

**Comment by carlpeaslee** [comment]
Thanks @michielvanhaverbeke! 

Ok, I've got an idea: I'm going to open another issue and tag you in it and close this one. Meet you there.
